In [3]:
# NumPy Arithmetic Functions Example (Single Cell)

import numpy as np

# Creating two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)



Array A: [10 20 30 40]
Array B: [1 2 3 4]


In [4]:
# Addition
print("\nAddition (np.add):")
print(np.add(a, b))





Addition (np.add):
[11 22 33 44]


In [5]:
# Subtraction
print("\nSubtraction (np.subtract):")
print(np.subtract(a, b))


Subtraction (np.subtract):
[ 9 18 27 36]


In [6]:

# Multiplication
print("\nMultiplication (np.multiply):")
print(np.multiply(a, b))



Multiplication (np.multiply):
[ 10  40  90 160]


In [7]:
# Division
print("\nDivision (np.divide):")
print(np.divide(a, b))



Division (np.divide):
[10. 10. 10. 10.]


In [8]:

# Power
print("\nPower (np.power):")
print(np.power(a, b))




Power (np.power):
[     10     400   27000 2560000]


In [9]:
# Modulus
print("\nModulus (np.mod):")
print(np.mod(a, b))




Modulus (np.mod):
[0 0 0 0]


In [10]:
# Floor Division
print("\nFloor Division (np.floor_divide):")
print(np.floor_divide(a, b))


Floor Division (np.floor_divide):
[10 10 10 10]


In [11]:

# Absolute Difference
print("\nAbsolute Difference (np.abs):")
print(np.abs(a - b))


Absolute Difference (np.abs):
[ 9 18 27 36]
